FROM mcr.microsoft.com/windows/servercore:ltsc2019 as download

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';$ProgressPreference='silentlyContinue';"]

RUN Invoke-WebRequest -OutFile nodejs.zip -UseBasicParsing "https://nodejs.org/dist/v12.4.0/node-v12.4.0-win-x64.zip"; `Expand-Archive nodejs.zip -DestinationPath C:\; `Rename-Item "C:\\node-v12.4.0-win-x64" c:\nodejs

FROM mcr.microsoft.com/windows/nanoserver:1803

WORKDIR C:\\nodejs
COPY --from=download C:\\nodejs\ .
RUN SETX PATH C:\\nodejs
RUN npm config set registry https://registry.npmjs.org/

WORKDIR /app

  # install and cache app dependencies
COPY /package.json /app/package.json

ENV NODE_ENV production
RUN npm install --production

COPY . /app
RUN npm run build

EXPOSE 3000

CMD [ "node", "/app/build/server.js" ]
